export default [{
	"borrowerName": "何腾凯",
	"borrowedAmount": 10,
	"repaymentDate": "2023-4-10",
	"repaymentAmount": 5,
	"residualAmount": 5,
	"remark": null,
},{
	"borrowerName": "磊爸",
	"borrowedAmount": 11,
	"repaymentDate": null,
	"repaymentAmount": 0,
	"residualAmount": 11,
	"remark": "最初是借了8w，小磊欠的2w他们给小磊还，所以是6w，村友世里的4w和大姑的1w，磊爸先还了，所以加一起是11w",
},{
	"borrowerName": "磊小姥",
	"borrowedAmount": 3,
	"repaymentDate": null,
	"repaymentAmount": 0,
	"residualAmount": 3,
},{
	"borrowerName": "张顺艺",
	"borrowedAmount": 10,
	"repaymentDate": "2023-4-6",
	"repaymentAmount": 3,
	"residualAmount": 7,
},{
	"borrowerName": "张侠",
	"borrowedAmount": 10,
	"repaymentDate": "2023-4-6",
	"repaymentAmount": 3,
	"residualAmount": 7,
},{
	"borrowerName": "英爸",
	"borrowedAmount": 5.8,
	"repaymentDate": null,
	"repaymentAmount": 0,
	"residualAmount": 5.8,
},{
	"borrowerName": "梁强",
	"borrowedAmount": 6,
	"repaymentDate": null,
	"repaymentAmount": 0,
	"residualAmount": 6,
},{
	"borrowerName": "李东蕊",
	"borrowedAmount": 5,
	"repaymentDate": null,
	"repaymentAmount": 0,
	"residualAmount": 5,
},{
	"borrowerName": "王志豪",
	"borrowedAmount": 3,
	"repaymentDate": null,
	"repaymentAmount": 0,
	"residualAmount": 3,
},]